# -*- coding: utf-8 -*-
"""AygazPB_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K1Uc4hXErqNlEN_oM8cg8-O1tX-Dmny5
"""

import random

def game_introduction():

    print("Welcome to Rock-Paper-Scissors-Pen!!! This is a game that just Pen option was added to Rock-Paper-Scissors. During the game, reaching score of 2 wins the game!"\
    "You can read all options for this game:\n\n"\
    "1. If you choose rock, you will win against scissors and pen but you will lose against paper. \n"\
    "2. If you choose paper, you will win against rock but you will lose against scissors and pen . \n"\
    "3. If you choose scissors, you will win against paper and pen but you will lose against rock. \n"\
    "4. If you choose pen, you will win against paper but you will lose against rock and scissors.\n\n"\
    "If you would like to exit, you can write q or Q! "\
    "Let's start!!!\n")


def pc_random_choose_game(): #End of the game, pc choose that it would like to play or not
    return random.choice([True,False])


def rock_paper_scissors_Erdem_Dağlı(): #main function
    game_introduction()

    elements=["Rock","Paper","Scissors","Pen"] #Options
    total_game=1
    player_game_won=0
    pc_game_won=0

    while True:
        total_round=1
        player_round_won=0
        pc_round_won=0

        while player_round_won<2 and pc_round_won<2:
            print(f"\n######  Game: {total_game}, Round: {total_round}  ######\n")

            user_choose=input("Your choose: ").capitalize() #If the user uses uppercase or lowercase letters, this function corrects it.

            if user_choose=='Q' and total_game==1 and total_round==1: #When player is in the first round and game and player wants quit
                print("\nYou exit before playing! It isn't fair!!")
                return
            elif user_choose=="Q" and total_round!=1:
                print("\nYou exit middle of the game. I think you have more important things to do :)")
                return

            if user_choose not in elements:
                print("\nInvalid input. Please try again.\n")
                continue

            pc_choose=random.choice(elements)
            print("PC choose: ",pc_choose)

            total_round+=1

            if user_choose==pc_choose: #Tie status
                print("Tie! You and PC chose same option!\n")

            elif (user_choose=="Rock" and pc_choose=="Scissors") or \
                (user_choose=="Rock" and pc_choose=="Pen") or \
                (user_choose=="Paper" and pc_choose=="Rock") or \
                (user_choose=="Scissors" and pc_choose=="Paper") or \
                (user_choose=="Scissors" and pc_choose=="Pen") or \
                (user_choose=="Pen" and pc_choose=="Paper"):
                print("You won this round!\n") #player's winning probabilities
                player_round_won+=1

            else:
                print("PC won this round!\n")
                pc_round_won+=1

            print(f"Your score: {player_round_won}, PC's score: {pc_round_won}\n")
            print("######################################\n") #to look better

        total_game+=1

        if player_round_won==2: #player's winning status
            print("You won the game! You are just lucky :)\n")
            player_game_won+=1
        else:
            print("PC won the game! Maybe another game you will win, maybe... ")
            pc_game_won+=1

        print(f"\nYour won game: {player_game_won}, PC's won game: {pc_game_won}")

        continue_game=input("\nWould you like to play another game? (y/n): ").upper() #for uppercase

        if continue_game!= "Y" and not pc_random_choose_game():
            print("\nGame is over! Thanks for everthing :) )")
            break
        elif continue_game== "Y" and not pc_random_choose_game():
            print("\nYou wanted play but PC didn't :/")
            break

rock_paper_scissors_Erdem_Dağlı()